version: '2'

services:
  postgres:
    image: kiasaki/alpine-postgres
    container_name: atlas_perf_postgres_2_bobby_is_worried
    environment:
       POSTGRES_PASSWORD: palantir
       POSTGRES_USER: palantir
       POSTGRES_DB: atlas
    network_mode: host
